// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  button: dynamic(() => import("./HomeButtons")),
  hero: dynamic(() => import("./Hero")),
};
